---
- hosts: collocated
  remote_user: root

  tasks:
  - name: Test connection to servers
    ping:

  - name: Create SSD Volume Groups
    lvg:
      vg: "{{ item.value.name }}"
      pvs: "/dev/{{ item.key }}"
    loop: "{{ drives.ssd|dict2items }}"

  - name: Create SSD Logical Volumes (db)
    lvol:
      vg: "{{ item.value.name }}"
      lv: "{{ item.value.db_lv }}"
      size: "{{ db_size }}"
    loop: "{{ drives.ssd|dict2items }}"

  - name: Create SSD Logical Volumes (wal)
    lvol:
      vg: "{{ item.value.name }}"
      lv: "{{ item.value.wal_lv }}"
      size: "{{ wal_size }}"
    loop: "{{ drives.ssd|dict2items }}"

  - name: Create SSD Logical Volumes (data)
    lvol:
      vg: "{{ item.value.name }}"
      lv: "{{ item.value.name }}"
      size: "100%FREE"
    loop: "{{ drives.ssd|dict2items }}"
